# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 20:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Avaliador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Criterios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=1000)),
                ('peso', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEntrega', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Etapas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=1000)),
                ('entrega', models.DateField()),
                ('especificacao', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricaoprojeto', models.CharField(max_length=1000)),
                ('nomeprojeto', models.CharField(max_length=1000)),
                ('alunos', models.ManyToManyField(to='Api.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('senha', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=100)),
                ('especificacao', tinymce.models.HTMLField()),
                ('descricao', models.CharField(max_length=1000)),
                ('ativo', models.BooleanField()),
                ('disciplinas', models.ManyToManyField(to='Api.Disciplinas')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Apresentacao',
            fields=[
                ('etapas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Api.Etapas')),
                ('criterios', models.ManyToManyField(to='Api.Criterios')),
            ],
            bases=('Api.etapas',),
        ),
        migrations.CreateModel(
            name='AvaliacaoAluno',
            fields=[
                ('avaliacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Api.Avaliacao')),
            ],
            bases=('Api.avaliacao',),
        ),
        migrations.CreateModel(
            name='AvaliacaoGrupo',
            fields=[
                ('avaliacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Api.Avaliacao')),
            ],
            bases=('Api.avaliacao',),
        ),
        migrations.AddField(
            model_name='grupo',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Projeto'),
        ),
        migrations.AddField(
            model_name='etapas',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Projeto'),
        ),
        migrations.AddField(
            model_name='entregas',
            name='Etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Etapas'),
        ),
        migrations.AddField(
            model_name='entregas',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Aluno'),
        ),
        migrations.AddField(
            model_name='avaliador',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Pessoa'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='avaliador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Avaliador'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='criterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Criterios'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Pessoa'),
        ),
        migrations.AddField(
            model_name='avaliacaogrupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Grupo'),
        ),
        migrations.AddField(
            model_name='avaliacaoaluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Aluno'),
        ),
    ]
